# Generated by Django 3.2.8 on 2021-11-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRankingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitedtrails', models.FloatField()),
                ('userid', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Level', models.FloatField()),
            ],
        ),
    ]
