# Generated by Django 3.2.8 on 2021-11-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancequery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrankingmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
