# Generated by Django 3.2.8 on 2021-11-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancequery', '0002_alter_userrankingmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendlistmodel',
            fields=[
                ('TrailName', models.CharField(max_length=150)),
                ('State', models.CharField(max_length=2)),
                ('DifficultyRating', models.IntegerField()),
                ('AvgRating', models.FloatField()),
                ('Features', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='userrankingmodel',
            old_name='Level',
            new_name='Difficulty',
        ),
        migrations.RenameField(
            model_name='userrankingmodel',
            old_name='firstname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='userrankingmodel',
            old_name='lastname',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='userrankingmodel',
            old_name='userid',
            new_name='UserID',
        ),
        migrations.RemoveField(
            model_name='userrankingmodel',
            name='visitedtrails',
        ),
        migrations.AddField(
            model_name='userrankingmodel',
            name='VisitedTrails',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
