# Generated by Django 3.2.8 on 2021-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancequery', '0003_auto_20211107_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrankingmodel',
            name='Difficulty',
            field=models.IntegerField(),
        ),
    ]
