# Generated by Django 3.2.8 on 2021-11-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancequery', '0004_alter_userrankingmodel_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrankingmodel',
            name='Difficulty',
            field=models.FloatField(),
        ),
    ]
