# Generated by Django 3.2.8 on 2021-11-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancequery', '0005_alter_userrankingmodel_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrankingmodel',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userrankingmodel',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='userrankingmodel',
            name='UserID',
            field=models.IntegerField(),
        ),
    ]
