# Generated by Django 3.2.8 on 2021-11-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailinfo',
            fields=[
                ('trailid', models.IntegerField(db_column='TrailID', primary_key=True, serialize=False)),
                ('trailname', models.CharField(blank=True, db_column='TrailName', max_length=150, null=True)),
                ('areaname', models.CharField(blank=True, db_column='AreaName', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=2, null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('popularity', models.FloatField(blank=True, db_column='Popularity', null=True)),
                ('length', models.FloatField(blank=True, db_column='Length', null=True)),
                ('elevationgain', models.FloatField(blank=True, db_column='ElevationGain', null=True)),
                ('difficultyrating', models.IntegerField(blank=True, db_column='DifficultyRating', null=True)),
                ('routetype', models.CharField(blank=True, db_column='RouteType', max_length=20, null=True)),
                ('avgrating', models.FloatField(blank=True, db_column='AvgRating', null=True)),
                ('features', models.CharField(blank=True, db_column='Features', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TrailInformation',
                'managed': False,
            },
        ),
    ]
